app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField, DateTimeField
from wtforms.validators import Required, Length

class PitchForm(FlaskForm):

    title = StringField('Title of your pitch', validators=[Required()])
    content = TextAreaField('Content', validators=[Required(), Length(min=6, max=255, message="Username should be more than 6 characters")])
    # date = DateTimeField('Date')
    category = SelectField('Select a category', choices=[('31', 'Job Pitches'), ('27', 'Movie Pitches'), ('26', 'Product Pitches'), ('32', 'Motivation Pitches')])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    content = TextAreaField('Content', validators=[Required()])
    submit = SubmitField('Comment')

class CategoryForm(FlaskForm):
    name = StringField('Name', validators=[Required()])
    submit = SubmitField('Submit')

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views, forms

app/main/views.py
from flask import render_template, redirect, url_for, abort, request
from .forms import PitchForm, CommentForm, CategoryForm
from ..auth.forms import UpdateForm
from . import main
from .. import photos, db
from ..models import Pitch, Category, User, Comment
from flask_login import login_required, current_user

@main.route('/', methods=['GET', 'POST'])
def index():
    title = "Pitch"
    movie_pitches = Pitch.get_pitches(1)
    product_pitches = Pitch.get_pitches(2)
    job_pitches = Pitch.get_pitches(3)
    motivation_pitches = Pitch.get_pitches(4)
    return render_template('main/index.html', title=title, movie_pitches=movie_pitches, product_pitches=product_pitches, job_pitches=job_pitches, motivation_pitches=motivation_pitches )

@main.route('/addcat', methods=['POST', 'GET'])
@login_required
def add_cat():
    form = CategoryForm()
    if form.validate_on_submit():
        name = form.name.data
        cat = Category(name=name)
        cat.save_category()
        return redirect(url_for('main.add_pitch'))
    return render_template('main/create_cat.html', form=form)

@main.route('/add', methods= ['GET', 'POST'])
@login_required
def add_pitch():
    form = PitchForm()
    categories = Category.get_all_cats()

    if request.method == 'POST':
        title = request.form['title']
        content = request.form['content']
        cate = request.form['category']
        pitch = Pitch(title=title, content=content, category_id=cate, user=current_user)
        pitch.save_pitch()
        return redirect(url_for('main.index'))
    return render_template('main/create_pitch.html', pitch_form=form, categories=categories)

    # if form.validate_on_submit():
    #     title = form.title.data
    #     content = form.content.data
    #     category = form.category.data
    #     pitch = Pitch(title=title, content=content, category_id=category, user=current_user)
    #     pitch.save_pitch()
    #     return redirect(url_for('main.index'))
    # return render_template('main/create_pitch.html', pitch_form=form, categories=categories)


@main.route('/pitch/<int:pitch_id>')
def display_pitch(pitch_id):
    pitch = Pitch.get_pitch_by_id(pitch_id)
    comments= Comment.get_all_comments(pitch_id)
    return render_template('main/pitch.html', pitch=pitch, comments=comments)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(name = uname).first()

    if user is None:
        abort(404)
    return render_template('profile/profile.html', user=user)

@main.route('/user/<uname>/update', methods= ['GET', 'POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(name=uname).first()
    update_form = UpdateForm()
    if user is None:
        abort(404)

    if update_form.validate_on_submit():
        user.bio = update_form.bio.data
        User.update_user(user)
        return redirect(url_for('.profile', uname=user.name))
    return render_template('profile/update.html', update_form = update_form)

@main.route('/user/<uname>/update/pic', methods=['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(name = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile', uname=uname))

@main.route('/upvote/<int:pitch_id>')
@login_required
def upvote(pitch_id):
    pitch = Pitch.query.filter_by(id = pitch_id).first()
    if pitch.upvotes is None:
        pitch.upvotes = 0
        pitch.upvotes += 1
    else:
        pitch.upvotes += 1
    db.session.commit()
    return redirect(url_for('main.index'))
    
    
@main.route('/downvote/<int:pitch_id>')
@login_required
def downvote(pitch_id):
    pitch = Pitch.query.filter_by(id = pitch_id).first()
    if pitch.downvotes is None:
        pitch.downvotes = 0
        pitch.downvotes += 1
    else:
        pitch.downvotes += 1
    db.session.commit()
    return redirect(url_for('main.index'))

@main.route('/pitch//comment/new/<int:pitch_id>', methods=['GET', 'POST'])
@login_required
def comment_pitch(pitch_id):
    comment_form = CommentForm()
    pitch= Pitch.get_pitch_by_id(pitch_id)
    if comment_form.validate_on_submit():
        content = comment_form.content.data
        new_comment = Comment(content=content, pitch_id=pitch_id)
        db.session.add(new_comment)
        db.session.commit()

        return redirect(url_for('main.display_pitch', pitch_id=pitch_id))
    return render_template('main/pitch_comment.html', form = comment_form, pitch=pitch)

app/templates/main/create_cat.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="container">
    <div class="row">
        {{ wtf.quick_form(form) }}
    </div>   
</div>
{% endblock %}

app/templates/main/create_pitch.html
{% extends 'base.html'%}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="container">
    <div class="row">
        
    </div>   
    <div class="row">
        <form action = "/add" method = "post">
            <div class="form-group row">
              <label class="col-sm-4 col-form-label">Title of the pitch</label>
              <div class="col-sm-8">
                <input type="text" name = "title" class="form-control" id="dpname" placeholder="title">
              </div>
            </div>
           <div class="form-group row">
              <label class="col-sm-4 col-form-label">Content</label>
              <div class="col-sm-8">
                <textarea name="content" id="" class="form-control"></textarea>
            </div>
            </div>
            <div class="form-group row">
                  <label class = "col-sm-4 col-form-label"> select category</label>
                  <div class = "col-sm-8">
                    <select class="form-control" style="color: black;" name="category">                        
                        <option selected>Select a Category</option>
                            {% for category in categories %}
                            <option value="{{category.id}}">{{category.name}}</option>
                        {% endfor %}
                    </select>
                  </div>
            </div>       
              

            <div class = "form-group row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>

          </form>
        </div>
</div>
{% endblock %}

app/templates/main/index.html
{% extends 'base.html'%}
{% import 'main/macros.html' as macro%}
{% block content %}

<div class="container">
    <div class="row">
        <h3 style="border-bottom: 2px #d08e73 solid;">Job Pitches</h3>
        {{ macro.displayPitches(job_pitches) }} 
    </div>
    <div class="row mt-12">
        <h3 style="border-bottom: 2px #d08e73 solid;">Movie pitches</h3>
        {{ macro.displayPitches(movie_pitches) }} 

    </div>
    <div class="row mt-12">
        <h3 style="border-bottom: 2px #d08e73 solid;">Product pitches</h3>
        {{ macro.displayPitches(product_pitches) }} 

    </div>
    <div class="row mt-12">
        <h3 style="border-bottom: 2px #d08e73 solid;">Motivation pitches</h3>
        {{ macro.displayPitches(motivation_pitches) }} 

    </div>

</div>
{% endblock %}

app/templates/main/macros.html
{% macro displayPitches(pitch_list) %}
    {% for pitch in pitch_list %}
        <div class="col-md-4 card">
            <div class="card-header">
                <h4>{{pitch.title}}</h4> 
            </div>
            <div class="card-body">
                <p>{{pitch.content}}</p>
            </div>
            <div class="card-footer">
                <div class="react">
                    <a href="{{url_for('main.upvote', pitch_id=pitch.id)}}"><img src="https://img.icons8.com/cotton/24/000000/thumb-up--v1.png"/><span>{{pitch.upvotes}}</span></a>
                    <a href="{{url_for('main.downvote', pitch_id=pitch.id)}}"><img src="https://img.icons8.com/cotton/24/000000/thumbs-down--v4.png"/><span>{{pitch.downvotes}}</span></a>
                </div>                
                <a href="{{url_for('main.comment_pitch', pitch_id = pitch.id)}}"><button type="button" class="btn btn-info">Comment</button></a>
            </div>      
           
        </div>
    {% endfor %}
{% endmacro %}

app/templates/main/pitch.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                
            </div>
            <div class="col-md-4">
                <div class="row">
                    <h4>{{pitch.title}}</h4>
                    <p>{{pitch.content}}</p>
                </div>
                <h5>Comments</h5>
                <ul>
                    {% for comment in comments %}
                        <li>{{comment.content}}</li>
                    {% endfor %}
                </ul>
                
            </div>
        </div>
    </div>
{% endblock %}

app/templates/main/pitch_comment.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <h4>{{pitch.title}}</h4>
                <p>{{pitch.content}}</p>
            </div>
            <div class="col-md-4">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
{% endblock %}